### ISSUE TITLE
"more complicated things"

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-custom-selectors#12]
http://dev.w3.org/csswg/css-extensions/#custom-selectors

```css
// Arguments are specified with $foo.
// An arg before the pseudo-class captures the rest of the compound selector.
@custom-selector $rest:--n-siblings($n, $sel) {
  specificity: $sel;
  // assumes $sel is a selector, parses it and uses its specificity
  // otherwise, specificity is [0,1,0]
  expansion: $rest:nth-child(1 of $sel):nth-last-child($n of $sel),
    :nth-child(1 of $sel):nth-last-child($n of $sel) ~ $rest;
}
```

we need to check the spec sometimes about this :)
