### ISSUE TITLE
Two or more consecutive hyphens in selector outputs "undefined"

### ISSUE THREAD

**Issue by AntonTrollback** [postcss/postcss-custom-selectors#14]
```css
@custom-selector :--headings h1, h2, h3, h4, h5, h6;

.Type--centerBlocks :--headings {
  margin-left: auto;
  margin-right: auto;
}
```

outputs:
```css
undefined {
  margin-left: auto;
  margin-right: auto;
}
```
