### ISSUE TITLE
Wrong output when mixing selectors 

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-custom-selectors#15]
```css
@custom-selector :--button button, .button;
:--button a, b {}
```

gives

```css
button a,
.button a, b {}
```

~~Which doesn't seems correct.~~ (edit: it is)

This lead to a bug into cssnext where

```css
@custom-selector :--button button, .button;

:--button:matches(:focus) {}

:--button:matches(.is-focused, .is-broken) {}
```

gives

```css
button:focus,
.button:focus {}

button:matches(.is-focused,
.button.is-focused, button:matches(.is-focused,
.button.is-broken {}
```

It's probably because this plugin currently use `.selector` instead of `.selectors` when playing with selectors :)

Bug reported by @jaredadobe

**Comment by jaredadobe** [comment]
I am going to take a stab at fixing. Will get a chance in about 2 hours.

**Comment by yisibl** [comment]
The specification does not seem this syntax.

```
@custom-selector = @custom-selector <custom-selector> <selector> ;
<custom-selector> = <custom-arg>? : <extension-name> [ ( <custom-arg>+#? ) ]? ;
<custom-arg> = $ <ident-token> ;
```

**Comment by MoOx** [comment]
Oh... In fact I say 

```css
button a,
.button a, b {}
```

was incorrect but it is not.

But the second example will matches is still wrong.
We should throw a exception if spec doesn't allow that, or make it like we might expect:

```css
button:matches(.is-focused,.is-broken),
.button:matches(.is-focused,.is-broken) {}
```
