### ISSUE TITLE
Use the postcss-selector-matches

### ISSUE THREAD

**Issue by yisibl** [postcss/postcss-custom-selectors#16]
In order to support more complex cases, We can use  the postcss-selector-matches to transform.

@MoOx Do you feel that you are directly dependent on another plugin?

```css
/* input: */
@custom-selector :--any-link :link, :visited;
@custom-selector :--heading h1, h2, h3;

:--heading > a:--any-link {
  color: red;
}

/* Then use the postcss-selector-matches to transform: */
:matches(h1, h2, h3) > a:matches(:link, :visitedk) {
  color: red;
}

/* output: */
h1 > a:link, h2 > a:link, h3 > a:link, h1 > a:visited, h2 > a:visited, h3 > a:visited {
  color: red;
}
```
