### ISSUE TITLE
lineBreak does not respect indentation

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-custom-selectors#18]
```css
@custom-selector :--heading h1, h2, h3, h4, h5, h6;

  article :--heading + p { 
    margin-top: 0;
  }
```
output

```css
article h1 + p,
article h2 + p,
article h3 + p { 
    margin-top: 0;
  }
```

but should output

```css
  article h1 + p,
  article h2 + p,
  article h3 + p { 
    margin-top: 0;
  }
```

You probably just need to join selector with \n + rule.before
