### ISSUE TITLE
Using multiple custom-selectors in one selector does not work

### ISSUE THREAD

**Issue by topaxi** [postcss/postcss-custom-selectors#19]
For example this:

```css
@custom-selector :--button-types
  .btn-primary,
  .btn-success,
  .btn-info,
  .btn-warning,
  .btn-danger;

:--button-types, :--button-types:active {
  color: white;
}
```

compiles to this:

```css
.btn-primary, :--button-types:active,
.btn-success, :--button-types:active,
.btn-info, :--button-types:active,
.btn-warning, :--button-types:active,
.btn-danger, :--button-types:active {
  color: white;
}
```

instead of this:

```css
.btn-primary, .btn-primary:active,
.btn-success, .btn-success:active,
.btn-info, .btn-info:active,
.btn-warning, .btn-warning:active,
.btn-danger, .btn-danger:active {
  color: white;
}
```

**Comment by yisibl** [comment]
https://github.com/postcss/postcss-custom-selectors#multiple-selectors

**Comment by MoOx** [comment]
Nice :)

**Comment by topaxi** [comment]
I'm pretty sure this worked before, might be a cssnext update that caused this but:

```css
@custom-selector :--foobar .foo, .bar;
@custom-selector :--baz .baz;

:--foobar > :--baz {
  color: red;
}
```

Isn't working for me anymore and now produces:

```css
.foo,
.bar {
  color: red;
}
```

Instead of:

```css
.foo > .baz,
.bar > .baz {
  color: red;
}
```

Is this the same limitation or just a regression?

cssnext 1.7.1 with postcss-custom-selectors 2.1.0

**Comment by topaxi** [comment]
Okay the comment above is definitely a cssnext problem, seems to be working with plain postcss-custom-selectors.

**Comment by MoOx** [comment]
https://github.com/cssnext/cssnext/issues/163#issuecomment-114843053

**Comment by topaxi** [comment]
So the case above was a playground/firefox issue. I tried to simplify the selectors I got and now have a failing case which definitely fails in postcss-custom-selectors and probably isn't related to cssnext.

input.css:
```css
@custom-selector :--fizzbuzz .fizz, .buzz;
@custom-selector :--foobar .foo, .bar;

:--fizzbuzz > :--foobar {
  color: red;
}
```

output:
```css
.fizz > .foo,
.fizz > .bar,
.buzz > .foo,
.buzz > .bar {
  color: red;
}
```

actual:
```css
.fizz > .foo,,
.fizz > .bar,
.buzz > .foo,

.buzz > .bar {
  color: red;
}
```
