### ISSUE TITLE
Warning: "The selector X is undefined"

### ISSUE THREAD

**Issue by Semigradsky** [postcss/postcss-custom-selectors#24]
**cssnext: 1.8.0**

Input:
```css
@custom-selector :--modal .ReactModal__Overlay;
@custom-selector :--modal-content .ReactModal__Content;

:--modal-content.users {
  width: 400px;
}
```

Warning:
> users.css:4:1: The selector ':--modal-content' is undefined

**Comment by Semigradsky** [comment]
For this input warning not showed:
```css
@custom-selector :--modal-content .ReactModal__Content;

:--modal-content.users {
  width: 400px;
}
```
