### ISSUE TITLE
Not valid output

### ISSUE THREAD

**Issue by Semigradsky** [postcss/postcss-custom-selectors#25]
**cssnext: 1.8.0**

Input:
```css
@custom-selector :--modal .ReactModal__Overlay;
@custom-selector :--modal-content .ReactModal__Content;

:--modal-content.users {
  width: 400px;
}
```

Output:
```css
.ReactModal__Content {
  width: 400px;
}
```

**Comment by Semigradsky** [comment]
In **cssnext 1.6.0** (postcss-custom-selectors 1.1.1) another output:
```css
undefined {
  width: 400px;
}
```

Maybe that is helped.

**Comment by Semigradsky** [comment]
For this input output is valid:
```css
@custom-selector :--modal-content .ReactModal__Content;

:--modal-content.users {
  width: 400px;
}
```
