### ISSUE TITLE
custom selectors with nesting

### ISSUE THREAD

**Issue by leiming** [postcss/postcss-custom-selectors#30]
I use [cssnest](http://cssnext.io/) which use this plugin and [postcss-nesting](https://github.com/jonathantneal/postcss-nesting).

```css
/* custom selectors and nesting */
@custom-selector :--heading .heading;
:--heading { 
  margin-top: 0;

  @nest &-small {
    margin-top: 2px;
  }

}
```

expect:
```css
/* custom selectors and nesting */
.heading { 
  margin-top: 0

}
.heading-small { 
  margin-top: 2px
}
```

actual:
```css
/* custom selectors and nesting */
.heading { 
  margin-top: 0

}
:--heading-small { 
  margin-top: 2px

}
```

@yisibl @MoOx , could you tell me the proper syntax to solve this problem?
