### ISSUE TITLE
custom selectors are not applied when used in combination with postcss-nesting

### ISSUE THREAD

**Issue by andrixb** [postcss/postcss-custom-selectors#33]
Hello 

I've been trying to use this plugin in combination with the `postcss-nesting` plugin but I'm getting an unexpected result.

```css
@custom-selector :--class .test;

:--class {
    @nest &__base {
        width: 100%;
    }
    @nest &__container {
      background-color: red;
    }
}
```

expected:
```css
.test__base {
   width: 100%;
}

.test__container {
  background-color: red;
}
```

but it is actually produced this:
```css
:--class__base {
    width: 100%;
}
```

Any thoughts regarding this issue? 

Many Thanks
