### ISSUE TITLE
Incorrect indentation and spaces

### ISSUE THREAD

**Issue by Semigradsky** [postcss/postcss-custom-selectors#34]
Version: `4.0.1`

Input:
```css
@custom-selector :--button .button;

:--button {
  & i {
    color: black;
  }
}
```

Expected result:
```css
.button i {
  color: black
}
```

Actual result:
```css
.button i{
    color: black
}
```
