### ISSUE TITLE
Iterate over each item in a selector?

### ISSUE THREAD

**Issue by smth** [postcss/postcss-custom-selectors#36]
Is it possible to iterate over each item in a selector? Here's an example of the use case I'm thinking of (maybe there's another way to achieve it?). Say you have:

```
@custom-selector :--button
  button,
  .button;

@custom-selector :--disabled
  :disabled,
  .disabled;
```

and you wanted to end up with:

```css
button:not(:disabled):not(.disabled),
.button:not(:disabled):not(.disabled) {
    /* some styles */
}
```

As opposed to
```css
button:not(:disabled),
button:not(.disabled),
.button:not(:disabled),
.button:not(.disabled) {
    /* some styles */
}
```
