### ISSUE TITLE
Not working with complex nesting (@nest)

### ISSUE THREAD

**Issue by smth** [postcss/postcss-custom-selectors#41]
When used in combination with `postcss-nesting`, custom selectors using `@nest` do not get properly transpiled.

```css
@custom-selector :--parent
  @nest .parent &;

.child {
  :--parent {
    /* styles */
  }
}
```

Results in

```css 
.child {
  @nest .parent & {
    /* styles */
  }
}
```

Instead of the expected

```css
.parent .child {
  /* styles */
}
```

**Comment by roshecode** [comment]
This does not work as well:
```css
@custom-selector :--view-m [data-view-size=m];

.view {
  @nest :--view-m & {
    background: red;
  }
}
```
Results in
```css
:--view-m .view {
    background: red
}
```
instead of the expected
```css
[data-view-size=m] .view {
    background: red
}
```

**Comment by wesleyboar** [comment]
I'd noticed in the past that the order of `postcss` plugins mattered greatly. And PostCSS plugin test cases did not test combination with other plugins.[^1] Is plugin load order still relevant?[^2] In what order were your plugins loaded?[^3]

[^1]: Skimming https://github.com/postcss/postcss/issues/764 and https://github.com/postcss/postcss/issues/296, I can't tell if order is still a user responsibility.
[^2]: For a plugin to test its order with another plugin is arguably outside of the scope of any plugin.[^4]
[^3]: I think for both comments, `postcss-custom-selectors` should come first.
[^4]: And `postcss` itself would have quite the task to test the order of every plugin that appears.

**Comment by thewilkybarkid** [comment]
I've just run into this; I've tried with `postcss-nesting` before and after this plugin, and get the same result.

```css
@custom-selector :--button button, [type='submit'], [type='button'], [type='reset'];

:--button,
.button {
  @nest :not(:--button, .button) + & {
    margin-block-start: var(--space-l);
  }
}
```

becomes

```css
:not(:--button, .button) + :is(button, [type="submit"], [type="button"], [type="reset"], .button) {
  margin-block-start: var(--space-l);
}
```

rather than the expected

```css
:not(button, [type="submit"], [type="button"], [type="reset"], .button) + :is(button, [type="submit"], [type="button"], [type="reset"], .button) {
  margin-block-start: var(--space-l);
}
```
