### ISSUE TITLE
Selector starting with numeral transpiles incorrectly

### ISSUE THREAD

**Issue by nekitk** [postcss/postcss-custom-selectors#43]
```css
@custom-selector :--3xl .3xl;

:--3xl {
  font-size: 46px;
}
```

Expected result:
```css
.3xl {
  font-size: 46px;
}
```

Actual result:
```css
@custom-selector :--3xl .3xl;

class=css-var>:--3xl {
  font-size: 46px;
}
```

[Codepen](https://codepen.io/nekitk/pen/rNVOXLv)

**Comment by Semigradsky** [comment]
The same for extension name contains only dashes:
```css
@custom-selector :------ .xl; 

:------ {
  font-size: 46px;
}
```

Actual result:
```css
@custom-selector :------ .xl; 

class=css-var>:------ {
  font-size: 46px;
}
```

But this extension name is correct by spec (https://drafts.csswg.org/css-extensions/#extension-name)
