### ISSUE TITLE
Expand existing custom selectors in selector definition

### ISSUE THREAD

**Issue by neatonk** [postcss/postcss-custom-selectors#5]
It should be possible to define one custom selector based on another custom selector, like so:

Input:

``` css
@custom-selector --heading h1, h2, h3, h4, h5, h6;
@custom-selector --main-heading main > --heading;
--main-heading {
  font-style: italic;
}
```

Expected output:

``` css
main > h1,
main > h2,
main > h3,
main > h4,
main > h5,
main > h6 {
  font-style: italic;
}
```

Actual output:

``` css
main > --heading {
  font-style: italic;
}
```
