### ISSUE TITLE
custom selectors are pseudo classes

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-custom-selectors#6]
Should be

```css
@custom-selector :--heading h1, h2, h3, h4, h5, h6;

:--heading { /* styles for all headings */ }
:--heading + p { /* more styles */ }
```
http://dev.w3.org/csswg/css-extensions/#example-5b616cc6

We need to support that asap and add a warning message to deprecate previous behavior.
I will try to tackle this.
