### ISSUE TITLE
usage with a class name selector that contains a double hyphens output a undefined selector

### ISSUE THREAD

**Issue by simonsmith** [postcss/postcss-custom-selectors#7]
The following code:

``` css
@custom-selector --heading h1, h2, h3, h4, h5, h6;

.Container--main --heading {
  margin-bottom: 15px;
}
```

yields:

``` css
undefined {
  margin-bottom: 15px;
}
```

I would expect:

``` css
.Container--main h1,
.Container--main h2,
.Container--main h3,
.Container--main h4,
.Container--main h5,
.Container--main h6 {
  margin-bottom: 15px;
}
```
